version: "3"
services:
  consensus-bn:
    build: ./${CONSENSUS_NODE}
    ports:
      - "${CONSENSUS_DISC}:9000/tcp"
      - "${CONSENSUS_DISC}:9000/udp"
    expose:
      - 5052
      - 5054
    environment:
      - ETH2_TESTNET
    volumes:
      - ./${CONSENSUS_NODE}/run:/home/beacon/run
      - ./shared/:/shared
    depends_on:
      - execution
      - proxy
  consensus-vc:
    build: ./${CONSENSUS_NODE}
    expose:
      - 5064
    environment:
      - ETH2_TESTNET
      - VALIDATOR_MNEMONIC
      - VALIDATOR_COUNT
      - VALIDATOR_GRAFFITI
      - FEE_RECIPIENT
    volumes:
      - ./${CONSENSUS_NODE}/run:/home/beacon/run
      - ./shared/:/shared
    depends_on:
      - consensus-bn
  execution:
    build: ./${EXECUTION_NODE}
    environment:
      - ETH2_TESTNET
    ports:
      - "${EXECUTION_DISC}:30303/tcp"
      - "${EXECUTION_DISC}:30303/udp"
    expose:
      - 8545
      - 8560
      - 6060
    volumes:
      - ./${EXECUTION_NODE}/run:/home/eth1/run
      - ./shared/:/shared
  proxy:
    build: ./proxy
    expose:
      - 8560
    volumes:
      - ./proxy/run:/home/json_rpc_snoop/run
    depends_on:
      - execution
  prometheus:
    build: ./metrics/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090/tcp"
    expose:
      - 9090
    volumes:
      - ./metrics/run/prometheus/:/home/promuser
    depends_on:
      - execution
      - consensus-bn
  grafana:
    build: ./metrics/grafana
    ports:
      - "${GRAFANA_PORT}:3000/tcp"
    environment:
      - GF_PATHS_DATA=/home/grafuser/data
      - GF_PATHS_LOGS=/home/grafuser/data
    volumes:
      - ./metrics/run/grafana/:/home/grafuser
    depends_on:
      - prometheus

