version: "3"
services:
  consensus-bn:
    build: ./${CONSENSUS_NODE}/build
    ports:
      - "${CONSENSUS_DISC}:${CONSENSUS_DISC}/tcp"
      - "${CONSENSUS_DISC}:${CONSENSUS_DISC}/udp"
      - "6052:5052"
    environment:
      - TESTNET_REPO
      - ETH2_TESTNET
      - CONSENSUS_DISC
    volumes:
      - ./${CONSENSUS_NODE}/run:/home/beacon/run
      - ./shared/:/shared
    depends_on:
      - execution
  consensus-vc:
    build: ./${CONSENSUS_NODE}/build
    environment:
      - ETH2_TESTNET
      - TESTNET_REPO
      - VALIDATOR_MNEMONIC
      - VALIDATOR_COUNT
      - VALIDATOR_GRAFFITI
      - FEE_RECIPIENT
    volumes:
      - ./${CONSENSUS_NODE}/run:/home/beacon/run
      - ./shared/:/shared
    depends_on:
      - consensus-bn
  execution:
    build: ./${EXECUTION_NODE}/build
    environment:
      - ETH2_TESTNET
      - TESTNET_REPO
      - EXECUTION_DISC
    ports:
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/tcp"
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/udp"
      - "8545:8545"
    expose:
      - 8560
    volumes:
      - ./${EXECUTION_NODE}/run:/home/eth1/run
      - ./shared/:/shared

